# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the touchscreen drivers.
#

obj-$(CONFIG_TOUCHSCREEN_ST)	+= st/
obj-$(CONFIG_TOUCHSCREEN_FTS)	+= focaltech_touch/
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM)	+= synaptics_tcm/
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX) += synaptics_dsx/
obj-$(CONFIG_TOUCHSCREEN_NT36XXX)	+= nt36xxx/
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT)	+= atmel_mxt_ts.o
obj-$(CONFIG_TOUCHSCREEN_USB_COMPOSITE)	+= usbtouchscreen.o
