# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_QCOM_RTB) += msm_rtb.o
obj-$(CONFIG_IPC_LOGGING) += ipc_logging.o
ifdef CONFIG_DEBUG_FS
obj-$(CONFIG_IPC_LOGGING) += ipc_logging_debug.o
endif
obj-$(CONFIG_PREEMPTIRQ_TRACEPOINTS) += preemptirq_long.o
