# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the HID driver
#

obj-$(CONFIG_HID_AKSYS_QRD)	+= hid-aksys.o
obj-$(CONFIG_HID_PLAYSTATION)	+= hid-playstation.o
obj-$(CONFIG_HID_QVR)		+= hid-qvr.o hid-trace.o
