# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_USB_EHSET_TEST_FIXTURE)    += ehset.o
obj-$(CONFIG_USB_LINK_LAYER_TEST)	+= lvstest.o
obj-$(CONFIG_USB_REDRIVER_NB7VPQ904M)	+= ssusb-redriver-nb7vpq904m.o
