# SPDX-License-Identifier: GPL-2.0
# Qualcomm pin control drivers

obj-$(CONFIG_PINCTRL_MSM)	+= pinctrl-msm.o
obj-$(CONFIG_PINCTRL_QCOM_SPMI_PMIC) += pinctrl-spmi-gpio.o
obj-$(CONFIG_PINCTRL_QCOM_SPMI_PMIC) += pinctrl-spmi-mpp.o
obj-$(CONFIG_PINCTRL_SDMSHRIKE) += pinctrl-sdmshrike.o
obj-$(CONFIG_PINCTRL_SM6150) 	+= pinctrl-sm6150.o
obj-$(CONFIG_PINCTRL_SHIMA) += pinctrl-shima.o
obj-$(CONFIG_PINCTRL_YUPIK) += pinctrl-yupik.o
obj-$(CONFIG_PINCTRL_SCUBA) += pinctrl-scuba.o
obj-$(CONFIG_PINCTRL_SDXLEMUR) += pinctrl-sdxlemur.o
obj-$(CONFIG_PINCTRL_SDXNIGHTJAR) += pinctrl-sdxnightjar.o
obj-$(CONFIG_PINCTRL_MONACO) += pinctrl-monaco.o
obj-$(CONFIG_PINCTRL_SLPI) += pinctrl-slpi.o
obj-$(CONFIG_PINCTRL_DIREWOLF) += pinctrl-direwolf.o
obj-$(CONFIG_PINCTRL_BLAIR) += pinctrl-blair.o
obj-$(CONFIG_PINCTRL_HOLI) += pinctrl-holi.o
obj-$(CONFIG_PINCTRL_LAHAINA) += pinctrl-lahaina.o
