# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_QCOM_LAZY_MAPPING) += msm_dma_iommu_mapping.o
obj-$(CONFIG_IOMMU_DEBUG) += iommu-debug.o
obj-$(CONFIG_ARM_SMMU) += qcom-arm-smmu-mod.o
qcom-arm-smmu-mod-objs += arm-smmu.o arm-smmu-impl.o arm-smmu-qcom.o arm-smmu-debug.o
obj-$(CONFIG_QTI_IOMMU_SUPPORT) += iommu-logger.o
