# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_LEDS_AW2016)		+= leds-aw2016.o
obj-$(CONFIG_LEDS_QCOM_CLK)		+= leds-qcom-clk.o
obj-$(CONFIG_LEDS_QPNP_FLASH_V2)        += leds-qpnp-flash-v2.o
obj-$(CONFIG_LEDS_QPNP_VIBRATOR_LDO)	+= leds-qpnp-vibrator-ldo.o
obj-$(CONFIG_LEDS_QTI_FLASH)		+= leds-qti-flash.o
obj-$(CONFIG_LEDS_QTI_TRI_LED)		+= leds-qti-tri-led.o
