# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Bluetooth HCI device drivers.
#

obj-$(CONFIG_MSM_BT_POWER)	+= btpower.o

bt_fm_slim-objs	:= btfm_slim.o btfm_slim_codec.o btfm_slim_slave.o

obj-$(CONFIG_BTFM_SLIM)	+= bt_fm_slim.o
