# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel USB device drivers.
#

obj-$(CONFIG_USB_DWC3)		+= dwc3/
obj-y		+= misc/ host/
obj-$(CONFIG_USB_PD)		+= pd/
obj-$(CONFIG_USB_SUPPORT)	+= phy/
obj-$(CONFIG_TYPEC)		+= typec/
