# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_QCOM_SHOW_RESUME_IRQ)      += msm_show_resume_irq.o
obj-$(CONFIG_QCOM_MPM)			+= mpm.o
mpm-objs +=       qcom-mpm.o qcom-mpm-holi.o qcom-mpm-sdxnightjar.o qcom-mpm-monaco.o qcom-mpm-qcs405.o qcom-mpm-blair.o
