# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_POWER_RESET_QCOM_VM) += msm-vm-poweroff.o
obj-$(CONFIG_POWER_RESET_QCOM_DOWNLOAD_MODE) += qcom-dload-mode.o
obj-$(CONFIG_POWER_RESET_QCOM_REBOOT_REASON) += qcom-reboot-reason.o
