# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_PHY_QCOM_UFS)		+= phy-qcom-ufs.o
obj-$(CONFIG_PHY_QCOM_UFS_V3)           += phy-qcom-ufs-qmp-v3.o phy-qcom-ufs-qmp-v3-660.o
obj-$(CONFIG_PHY_QCOM_UFS_V4)		+= phy-qcom-ufs-qmp-v4-yupik.o phy-qcom-ufs-qmp-v4-lahaina.o phy-qcom-ufs-qmp-v4.o
obj-$(CONFIG_PHY_QCOM_UFS_QRBTC_SDM845) += phy-qcom-ufs-qrbtc-sdm845.o
