# SPDX-License-Identifier: GPL-2.0
#
# Makefile for sensor chip drivers.
#

obj-$(CONFIG_ARCH_QCOM)	+= qcom/
obj-$(CONFIG_THERMAL_TSENS)     += msm-tsens-driver.o
msm-tsens-driver-objs     := msm-tsens.o tsens2xxx.o tsens-dbg.o tsens-mtc.o tsens1xxx.o tsens-calib.o
