# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_CPU_FREQ_MSM)              += qcom-cpufreq.o
obj-$(CONFIG_ARM_QCOM_CPUFREQ_HW)	+= qcom-cpufreq-hw.o
obj-$(CONFIG_ARM_QCOM_CPUFREQ_HW_DEBUG)	+= qcom-cpufreq-hw-debug.o
