# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the i2c bus drivers.
#

obj-$(CONFIG_I2C_MSM_GENI)	+= i2c-msm-geni.o
obj-$(CONFIG_I2C_MSM_V2)        += i2c-msm-v2.o
obj-$(CONFIG_VIRTIO_I2C)	+= virtio-i2c.o
