# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_RPMSG_QCOM_GLINK_SLATECOM) += qcom_glink_slatecom.o
obj-$(CONFIG_RPMSG_QCOM_GLINK_SPSS) += qcom_glink_spss.o
obj-$(CONFIG_RPMSG_QCOM_SMD)	+= qcom_smd.o
