# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_QTI_BATTERY_CHARGER)	+= qti_battery_charger_main.o
qti_battery_charger_main-y += qti_battery_charger.o qti_typec_class.o
obj-$(CONFIG_QCOM_POWER_SUPPLY)		+= qcom/
