# SPDX-License-Identifier: GPL-2.0
#
# Makefile for IIO ADC drivers
#

obj-$(CONFIG_QCOM_SPMI_ADC5) += qcom-spmi-adc5.o
obj-$(CONFIG_QCOM_SPMI_ADC5_GEN3) += qcom-spmi-adc5-gen3.o
obj-$(CONFIG_QCOM_VADC_COMMON) += qcom-vadc-common.o
