# SPDX-License-Identifier: GPL-2.0
#
# Makefile for physical layer USB drivers
#
obj-$(CONFIG_USB_QCOM_EMU_PHY)		+= phy-qcom-emu.o
obj-$(CONFIG_MSM_QUSB_PHY)		+= phy-msm-qusb-v2.o phy-msm-qusb.o
obj-$(CONFIG_USB_MSM_SSPHY_QMP)		+= phy-msm-ssusb-qmp.o
obj-$(CONFIG_MSM_HSUSB_PHY)		+= phy-msm-snps-hs.o
